# Site settings
author: Wills
title: Wills Likes Computers
header-img: img/home-bg.png
email: richwblake@gmail.com
copyright_name: Wills
description: > # this means to ignore newlines until "baseurl:"
  Thoughts, or lack there of, on modern tech
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  richwblake

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
